#!/bin/bash
#
# Run klayout DRC on the chipalooza test chip, pre-fill 
# GDS is sg13cmos5l_ocd_chipalooza.gds.gz, top level cell name is
# sg13cmos5l_ocd_chipalooza.  The GDS at this pre-fill level is
# temporary, generated by scripts/run_gen_prefill_gds.sh
#
# Run this script from the validate/ directory.

export PDK_ROOT=${PDK_ROOT:-/home/tim/gits}
export PDK=${PDK:-ihp-sg13cmos5l}

klayout -b -zz -r ${PDK_ROOT}/${PDK}/libs.tech/klayout/tech/drc/ihp-sg13cmos5l.drc -rd input=../gds/sg13cmos5l_ocd_chipalooza.gds.gz -rd report=../validate/sg13cmos5l_ocd_chipalooza.lyrdb -rd feol=True -rd beol=True -rd conn_drc=True -rd wedge=True -rd run_mode=deep -rd thr=16 -rd topcell=sg13cmos5l_ocd_chipalooza

echo "Done!"
exit 0
