/* Generated by scripts/gen_xschem_sym.py -- do not edit.
 *
 * LVS view of RM_IHPSG13_1P_1024x8_c2_bm_bist:  ports named and ORDERED exactly
 * as the IHP CDL for this cell, which is what the extracted netlist and the
 * xschem symbol both use.
 */

module RM_IHPSG13_1P_1024x8_c2_bm_bist (
    input [9:0] A_ADDR,
    input [9:0] A_BIST_ADDR,
    input [7:0] A_BIST_BM,
    input A_BIST_CLK,
    input [7:0] A_BIST_DIN,
    input A_BIST_EN,
    input A_BIST_MEN,
    input A_BIST_REN,
    input A_BIST_WEN,
    input [7:0] A_BM,
    input A_CLK,
    input [7:0] A_DIN,
    input A_DLY,
    output [7:0] A_DOUT,
    input A_MEN,
    input A_REN,
    input A_WEN,
    inout VDD,
    inout VDDARRAY,
    inout VSS
);
endmodule
