/* Generated by scripts/gen_xschem_sym.py -- do not edit.
 *
 * LVS view of slot4_wrapper:  ports named and ORDERED exactly
 * as magic/slot4_wrapper.mag, which is what the extracted netlist and the
 * xschem symbol both use.
 *
 * The simulation view lives in verilog/rtl/slot4_wrapper.v and is NOT
 * interchangeable with this one.
 */

module slot4_wrapper (
    inout [0:0] s4_an,
    inout vss_1v2,
    inout s4_an_0_esd,
    inout vbias,
    input [23:0] dig_in,
    output [11:0] dig_out,
    inout ibias0,
    inout ibias1,
    inout analog_bus3,
    inout analog_bus2,
    inout analog_bus1,
    inout analog_bus0,
    inout vdd_1v2,
    inout vss_3v3,
    inout vdd_3v3,
    input enable,
    input clk,
    input reset
);
endmodule
