/* Generated by scripts/gen_xschem_sym.py -- do not edit.
 *
 * LVS view of slot7_wrapper:  ports named and ORDERED exactly as
 * magic/slot7_wrapper.mag, which is what the extracted netlist
 * and the xschem symbol both use.  The simulation view lives in
 * verilog/rtl/slot7_wrapper.v and is NOT interchangeable.
 */

module slot7_wrapper (
    inout vss_1v2,
    inout [0:1] s7_an,
    inout s7_an_0_esd,
    inout vbias,
    input [23:0] dig_in,
    output [11:0] dig_out,
    inout ibias1,
    inout ibias0,
    inout analog_bus0,
    inout analog_bus1,
    inout analog_bus2,
    inout analog_bus3,
    inout vdd_1v2,
    inout vss_3v3,
    inout vdd_3v3,
    input enable,
    input clk,
    input reset
);
endmodule
